task_manager/tasks/urls.py
from django.urls import path
from .views import (TasksListView,
                    TasksCreateView,
                    TasksUpdateView,
                    TasksDeleteView,
                    TaskView)

urlpatterns = [
    path('', TasksListView.as_view(), name='tasks_list'),
    path('create/', TasksCreateView.as_view(), name='tasks_create'),
    path('<int:pk>/', TaskView.as_view(), name='task_view'),
    path('<int:pk>/update/', TasksUpdateView.as_view(),
         name='tasks_update'),
    path('<int:pk>/delete/', TasksDeleteView.as_view(),
         name='tasks_delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, UserLoginView, UserLogoutView

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('', IndexView.as_view(), name='index'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('admin/', admin.site.urls),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

task_manager/tasks/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from task_manager.statuses.models import Status
from task_manager.labels.models import Label


class Task(models.Model):
    name = models.CharField(
        _('Name'),
        max_length=100,
        unique=True,
        help_text=_('Unique task name'),
        error_messages={
            'unique': _('Task with this name already exists'),
        }

    )
    description = models.TextField(
        _('Description'),
        blank=True,
        max_length=500,
        help_text=_('Detailed task description')
    )

    executor = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name='executor_tasks',
        verbose_name=_('Executor'),
        help_text=_('User responsible for the task')
    )

    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        related_name='created_tasks',
        verbose_name=_('Author'),
        help_text=_('User who created the task')
    )

    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        verbose_name=_('Status'),
        help_text=_('Current task status')
    )

    labels = models.ManyToManyField(
        Label,
        blank=True,
        verbose_name=_('Labels'),
        help_text=_('Current task label')
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')
        ordering = ['name']

    def __str__(self):
        return self.name

task_manager/tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'executor', 'status', 'labels']
        widgets = {
            'executor': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'labels': forms.SelectMultiple(attrs={
                'class': 'form-select',
                'multiple': True
            }),
        }

task_manager/tasks/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.db import IntegrityError
from django.utils.translation import gettext_lazy as _
from django.shortcuts import get_object_or_404, render, redirect
from .models import Task
from .forms import TaskForm
from django_filters.views import FilterView
from .filter import TaskFilter


class TasksListView(LoginRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/tasks_list.html'
    context_object_name = 'tasks'
    filterset_class = TaskFilter
    login_url = reverse_lazy('login')

    def get_queryset(self):
        return super().get_queryset().order_by('name')


class TaskView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/task_view.html'
    context_object_name = 'task'
    login_url = reverse_lazy('login')


class TasksCreateView(SuccessMessageMixin, CreateView):
    form_class = TaskForm
    template_name = 'tasks/tasks_create.html'
    success_url = reverse_lazy('tasks_list')
    success_message = _("Task created successfully!")

    def form_valid(self, form):
        try:
            form.instance.author = self.request.user
            response = super().form_valid(form)
            return response
        except IntegrityError:
            messages.error(self.request,
                           _("Task with this name already exists"))
            return self.render_to_response(self.get_context_data(form=form))


class TasksUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/tasks_update.html'
    success_url = reverse_lazy('tasks_list')
    success_message = _("Task updated successfully!")
    login_url = reverse_lazy('login')

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Task, pk=self.kwargs.get('pk'))

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()

        if not request.user.is_superuser and obj.author != request.user:
            messages.error(request, _("You can only update your own task"))
            return redirect('tasks_list')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        try:
            response = super().form_valid(form)
            return response
        except IntegrityError:
            messages.error(self.request,
                           _("Task with this name already exists"))
            return self.render_to_response(self.get_context_data(form=form))


class TasksDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Task
    template_name = 'tasks/tasks_confirm_delete.html'
    success_url = reverse_lazy('tasks_list')
    success_message = _("Task deleted successfully!")
    login_url = reverse_lazy('login')

    def get_object(self, queryset=None):
        return get_object_or_404(Task, pk=self.kwargs.get('pk'))

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()

        if not request.user.is_superuser and obj.author != request.user:
            messages.error(request, _("You can only delete your own task"))
            return redirect('tasks_list')
        return super().dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        if self.object.task_set.exists():
            messages.warning(self.request,
                             _("This task is currently "
                               "in use and cannot be deleted"))
            return HttpResponseRedirect(self.get_success_url())

        try:
            return super().delete(request, *args, **kwargs)
        except IntegrityError:
            messages.error(self.request,
                           _("Failed to delete task."))
            return render(self.request,
                          self.template_name,
                          self.get_context_data())

task_manager/tasks/templates/tasks/task_view.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate "Task View" %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>{% translate "Task View" %}</h1>

    <div class="card-header bg-secondary text-white">
        <h2>{{ task.name }}</h2>
    </div>

    <div class="card-body bg-light">
        <p>{{ task.description }}</p>
    </div>
    <hr>

    <div class="container">
        <div class="row p-1">
            <div class="col">{% translate "Author" %}</div>
            <div class="col">{{ task.author }}</div>
        </div>
        <div class="row p-1">
            <div class="col">{% translate "Executor" %}</div>
            <div class="col">{{ task.executor }}</div>
        </div>
        <div class="row p-1">
            <div class="col">{% translate "Status" %}</div>
            <div class="col">{{ task.status }}</div>
        </div>
        <div class="row p-1">
            <div class="col">{% translate "Created At" %}</div>
            <div class="col">{{ task.created_at }}</div>
        </div>
        <div class="row p-1">
            <div class="col">
                <h6>{% translate "Labels" %}</h6>
                {% for label in task.labels.all %}
                <ul>
                    <li>{{ label.name }}</li>
                </ul>
                {% endfor %}
            </div>
        </div>
        <div class="row p-1">
            <div class="col"><a href="{% url 'tasks_update' pk=task.id %}" class="btn btn-sm btn-warning">{% translate "Edit" %}</a></div>
            <div class="col"><a href="{% url 'tasks_delete' pk=task.id %}" class="btn btn-sm btn-danger">{% translate "Delete" %}</a></div>
        </div>
    </div>
</div>
{% endblock %}

task_manager/tasks/templates/tasks/tasks_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}{% translate "Delete Task" %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>{% translate "Delete Task" %}</h1>

    <p>{% translate "Are you sure you want to delete" %} "{{ object.name }}"?</p>

    <form method="post">
        {% csrf_token %}
        <div class="text-end">
            <button type="submit" class="btn btn-danger">{% translate "Yes, delete" %}</button>
            <a href="{% url 'tasks_list' %}" class="btn btn-secondary">{% translate "Cancel" %}</a>
        </div>
    </form>
</div>
{% endblock %}

task_manager/tasks/templates/tasks/tasks_create.html
{% extends 'base.html' %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}{% translate "Create Task" %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>{% translate "Create New Task" %}</h1>
    
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        
        <div class="text-end">
            <button type="submit" class="btn btn-primary">{% translate "Create" %}</button>
            <a href="{% url 'tasks_list' %}" class="btn btn-secondary">{% translate "Cancel" %}</a>
        </div>
    </form>
</div>
{% endblock %}

task_manager/tasks/templates/tasks/tasks_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate "Tasks List" %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>{% translate "Tasks List" %}</h1>

    <div class="mb-3">
        <a href="{% url 'tasks_create' %}" class="btn btn-primary">{% translate "Create Tasks" %}</a>
    </div>

    <form method="get" class="p-4 bg-light rounded border shadow-sm mb-4">
        <div class="mb-3">
          <label for="id_status" class="form-label">{% translate "Status" %}</label>
          {{ filter.form.status }}
        </div>
        <div class="mb-3">
          <label for="id_executor" class="form-label">{% translate "Executor" %}</label>
          {{ filter.form.executor }}
        </div>
        <div class="mb-3">
          <label for="id_labels" class="form-label">{% translate "Label" %}</label>
          {{ filter.form.labels }}
        </div>
        <div class="form-check mb-3">
          {{ filter.form.is_author }}
          <label for="id_is_author" class="form-check-label">{% translate "Your tasks" %}</label>
        </div>
        <button type="submit" class="btn btn-primary">{% translate "Show" %}</button>
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>{% translate "Name" %}</th>
                <th>{% translate "Status" %}</th>
                <th>{% translate "Author" %}</th>
                <th>{% translate "Executor" %}</th>
                <th>{% translate "Creation date" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td><a href="{% url 'task_view' pk=task.id %}">{{ task.name }}</a></td>
                <td>{{ task.status }}</td>
                <td>{{ task.author }}</td>
                {% if task.executor is None %}
                    <td></td>
                {% else %}
                    <td>{{ task.executor }}</td>
                {% endif %}
                <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
                <td>
                    <a href="{% url 'tasks_update' task.pk %}" class="btn btn-sm btn-warning">{% translate "Edit" %}</a>
                    <a href="{% url 'tasks_delete' task.pk %}" class="btn btn-sm btn-danger">{% translate "Delete" %}</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

task_manager/tasks/templates/tasks/tasks_update.html
{% extends 'base.html' %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}{% translate "Update Task" %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>{% translate "Update Task" %}</h1>
    
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        
        <div class="text-end">
            <button type="submit" class="btn btn-primary">{% translate "Change" %}</button>
            <a href="{% url 'tasks_list' %}" class="btn btn-secondary">{% translate "Cancel" %}</a>
        </div>
    </form>
</div>
{% endblock %}